/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ventanas;

/**
 *
 * @author bcastrof
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCentros1 = new javax.swing.JButton();
        bTrabajadores1 = new javax.swing.JButton();
        bVehiculos1 = new javax.swing.JButton();
        bPartes1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bCentros1.setText("Centros");
        bCentros1.setMaximumSize(new java.awt.Dimension(97, 23));
        bCentros1.setMinimumSize(new java.awt.Dimension(97, 23));
        bCentros1.setPreferredSize(new java.awt.Dimension(97, 23));
        bCentros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCentros1ActionPerformed(evt);
            }
        });
        getContentPane().add(bCentros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        bTrabajadores1.setText("Trabajadores");
        bTrabajadores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrabajadores1ActionPerformed(evt);
            }
        });
        getContentPane().add(bTrabajadores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 30));

        bVehiculos1.setText("Vehiculos");
        bVehiculos1.setToolTipText("");
        bVehiculos1.setPreferredSize(new java.awt.Dimension(97, 23));
        bVehiculos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVehiculos1ActionPerformed(evt);
            }
        });
        getContentPane().add(bVehiculos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 30));

        bPartes1.setText("Partes");
        bPartes1.setPreferredSize(new java.awt.Dimension(97, 23));
        bPartes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPartes1ActionPerformed(evt);
            }
        });
        getContentPane().add(bPartes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, 30));

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("SELECCIONE LO QUE QUIERE GESTIONAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCentros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCentros1ActionPerformed
        
        CentrosUd abrir = new CentrosUd();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bCentros1ActionPerformed

    private void bTrabajadores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrabajadores1ActionPerformed
        TrabajadoresUd abrir = new TrabajadoresUd();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bTrabajadores1ActionPerformed

    private void bVehiculos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVehiculos1ActionPerformed
        VehiculosUd abrir = new VehiculosUd();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bVehiculos1ActionPerformed

    private void bPartes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPartes1ActionPerformed
        /*PartesUd abrir = new ParteUd();*/
    }//GEN-LAST:event_bPartes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCentros1;
    private javax.swing.JButton bPartes1;
    private javax.swing.JButton bTrabajadores1;
    private javax.swing.JButton bVehiculos1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
